import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/farmer_model.dart';

class ReceiptFooter extends pw.StatelessWidget {
  final FarmerModel farmer;

  ReceiptFooter({
    required this.farmer,
  });

  @override
  pw.Widget build(pw.Context context) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [

        //---------------------------------------------------------
        // Remarks
        //---------------------------------------------------------

        if (farmer.remarks.isNotEmpty) ...[
          pw.Text(
            "Remarks",
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
            ),
          ),

          pw.SizedBox(height: 8),

          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(
                color: PdfColors.grey400,
              ),
              borderRadius:
                  pw.BorderRadius.circular(6),
            ),
            child: pw.Text(
              farmer.remarks,
              style: const pw.TextStyle(
                fontSize: 11,
              ),
            ),
          ),

          pw.SizedBox(height: 20),
        ],

        //---------------------------------------------------------
        // ACK
        //---------------------------------------------------------

        pw.Container(
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius:
                pw.BorderRadius.circular(6),
          ),
          child: pw.Row(
            children: [

              pw.Text(
                "Acknowledgement No",
                style: pw.TextStyle(
                  fontWeight:
                      pw.FontWeight.bold,
                ),
              ),

              pw.Spacer(),

              pw.Text(
                farmer.ackNo.isEmpty
                    ? "Pending"
                    : farmer.ackNo,
              ),
            ],
          ),
        ),

        pw.SizedBox(height: 40),

        //---------------------------------------------------------
        // Signature
        //---------------------------------------------------------

        pw.Row(
          children: [

            pw.Expanded(
              child: _signature(
                "Farmer Signature",
              ),
            ),

            pw.SizedBox(width: 40),

            pw.Expanded(
              child: _signature(
                "Survey Officer",
              ),
            ),

            pw.SizedBox(width: 40),

            pw.Expanded(
              child: _signature(
                "Authorized Officer",
              ),
            ),
          ],
        ),

        pw.SizedBox(height: 40),

        //---------------------------------------------------------
        // Declaration
        //---------------------------------------------------------

        pw.Container(
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            color: PdfColors.green50,
            borderRadius:
                pw.BorderRadius.circular(6),
          ),
          child: pw.Text(
            "I hereby declare that the information provided above "
            "is true and correct to the best of my knowledge.",
            textAlign: pw.TextAlign.justify,
            style: const pw.TextStyle(
              fontSize: 10,
            ),
          ),
        ),

        pw.SizedBox(height: 25),

        //---------------------------------------------------------
        // Footer
        //---------------------------------------------------------

        pw.Divider(),

        pw.SizedBox(height: 10),

        pw.Row(
          children: [

            pw.Text(
              "Generated by Crop Survey Management System",
              style: const pw.TextStyle(
                fontSize: 9,
              ),
            ),

            pw.Spacer(),

            pw.Text(
              DateFormat(
                "dd MMM yyyy  hh:mm a",
              ).format(
                DateTime.now(),
              ),
              style: const pw.TextStyle(
                fontSize: 9,
              ),
            ),
          ],
        ),

        pw.SizedBox(height: 5),

        pw.Center(
          child: pw.Text(
            "This is a computer generated receipt and does not require a physical signature.",
            style: const pw.TextStyle(
              fontSize: 8,
              color: PdfColors.grey700,
            ),
          ),
        ),
      ],
    );
  }

  //---------------------------------------------------------
  // Signature Widget
  //---------------------------------------------------------

  pw.Widget _signature(String title) {
    return pw.Column(
      children: [

        pw.Container(
          height: 45,
        ),

        pw.Divider(),

        pw.SizedBox(height: 4),

        pw.Text(
          title,
          style: const pw.TextStyle(
            fontSize: 10,
          ),
        ),
      ],
    );
  }
}