// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJWnHhzYE7xxcbfCcJ0cfB7qRK9NvzbG0',
    appId: '1:952048332441:web:b4bee8be89fb5bc4979208',
    messagingSenderId: '952048332441',
    projectId: 'crop-survey-sringeri-koppa',
    authDomain: 'crop-survey-sringeri-koppa.firebaseapp.com',
    storageBucket: 'crop-survey-sringeri-koppa.firebasestorage.app',
    measurementId: 'G-X1N5T4P1HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsl0U2spA4hNGCNH4q4V76VZobw3qWuoE',
    appId: '1:952048332441:android:3a8bd227ba31f4f8979208',
    messagingSenderId: '952048332441',
    projectId: 'crop-survey-sringeri-koppa',
    storageBucket: 'crop-survey-sringeri-koppa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9FuTIwtmssWAdyzxyBR2V_srtzovFgpE',
    appId: '1:952048332441:ios:11f37879899ca3c5979208',
    messagingSenderId: '952048332441',
    projectId: 'crop-survey-sringeri-koppa',
    storageBucket: 'crop-survey-sringeri-koppa.firebasestorage.app',
    iosBundleId: 'com.example.cropSurvey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9FuTIwtmssWAdyzxyBR2V_srtzovFgpE',
    appId: '1:952048332441:ios:11f37879899ca3c5979208',
    messagingSenderId: '952048332441',
    projectId: 'crop-survey-sringeri-koppa',
    storageBucket: 'crop-survey-sringeri-koppa.firebasestorage.app',
    iosBundleId: 'com.example.cropSurvey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJWnHhzYE7xxcbfCcJ0cfB7qRK9NvzbG0',
    appId: '1:952048332441:web:55e1d8cedb88c3aa979208',
    messagingSenderId: '952048332441',
    projectId: 'crop-survey-sringeri-koppa',
    authDomain: 'crop-survey-sringeri-koppa.firebaseapp.com',
    storageBucket: 'crop-survey-sringeri-koppa.firebasestorage.app',
    measurementId: 'G-0PVRH17X3V',
  );
}
